image bg01 = "backgrounds/metro.png"
image bg02 = "backgrounds/black-back.jpg"
image bg03 = "backgrounds/school-outside.png"
image bg04 = "backgrounds/school-inside-1.png"
image bg05 = "backgrounds/1st-grade-classroom.png"
image bg06 = "backgrounds/gwen-over.png"
image bg07 = "backgrounds/bicypark.png"
image bg08 = "backgrounds/bonnie-house.png"
