init python:

    amynames = ["Amy", "Amy Kingslay"]
    augustinenames = ["Augustine", "Augustine Hart", "Auggie"]
    biercenames = ["Bierce", "Bierce Gambino", "Bie"]
    carolnames = ["Caroline", "Caroline Rustman", "Carol"]
    chloenames = ["Chloe", "Chloe Clio"]
    celestenames = ["Celeste", "Celeste Heilsie", "Cell"]
    charlienames = ["Charlotte", "Charlotte Dewbie", "Charlie"]
    dellnames = ["Delana", "Delana Diem", "Delana Diem Cardinal von Cranenbroek", "Delana Cranenbroek", "Dell", "Diem"]
    jacksonnames = ["Jackson", "Jackson Nyrock", "Jackie"]
    julietnames = ["Juliet", "Juliet Sinkoon"]
    kaelynnames = ["Kaelyn", "Kaelyn Ravat"]
    leonames = ["Leo", "Leonard", "Leo Beaurenaire", "Leonard Beaurenaire"]
    marienames = ["Marie", "Marie Poplar"]
    nigelnames = ["Nigel", "Nigel Weekes", "Deathcore", "Kitten"]
    nonanames = ["Nona", "Nona Konovalova"]
    paigenames = ["Paige", "Paige Tyshe"]
    ramonanames = ["Ramona", "Ramona Schweep", "Ram"]
    rexnames = ["Rex", "Rex Cherry", "Cherry Boy"]
    roxynames = ["Roxy", "Roxy Raymond", "Rox"]
    tatenames = ["Tate", "Tate Skinplet", "Skincrawler"]
    viktornames = ["Viktor", "Viktor Mault", "Vik"]
