init python:

    andynames = ["Andy", "Andy Williams"]
    bonnienames = ["Bonnie", "Bonnie Mee", "Bon"]
    chesternames = ["Chester", "Chester Lindemann"]
    dominicnames = ["Dominic", "Dominic Hooplan", "Dom"]
    ebonynames = ["Ebony", "Ebony Collins"]
    fayenames = ["Faye", "Faye Ruby"]
    franznames = ["Franz", "Franz Momsen"]
    kanenames = ["Kane", "Kane Ravat"]
    marshallnames = ["Marshall", "Marshall Dior"]
    mattnames = ["Matt", "Matt Raven", "Matthew", "Matthew Raven"]
    mikanames = ["Mikaella", "Mikaella Nicolette", "Mika"]
    mikenames = ["Michael", "Mike", "Michael Weekes", "Mike Weekes"]
    olivernames = ["Oliver", "Oli", "Oliver Shaw"]
    ronnienames = ["Ronald", "Ronnie", "Ronald Reynolds", "Ronnie Reynolds"]
    scottnames = ["Scott", "Scott McCracken", "Scotty"]
    taylornames = ["Taylor", "Taylor Lanza"]
    tinanames = ["Tina", "Tina Mercury"]
    vickynames = ["Vicky", "Vic", "Vicky Spears"]
    vickydeadnames = ["Damon", "Damon Spears"]
